import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {atom, useAtom} from 'jotai'
import {useHydrateAtoms} from 'jotai/utils'

const inter = Inter({ subsets: ['latin'] })

interface Pokemon{
  id:number;
  name:string;
  image:string
}

const pokemonAtom = atom<Pokemon[]>([])

const filterAtom = atom("");

const filteredPokemon = atom((get) => 
  get(pokemonAtom).filter((pokemon) =>
    pokemon.name.toLowerCase().includes(get(filterAtom).toLowerCase())))

export async function  getServerSideProps(){
  const res = await fetch("https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json");
  return{
    props:{
      initialPokemon:await res.json(),
    },
  }
}

export default function Home({initialPokemon}:{initialPokemon:Pokemon[]}) {

  useHydrateAtoms([[pokemonAtom,initialPokemon]] as const)

  const [pokemon] = useAtom(filteredPokemon)
  const [filter,setFilter] = useAtom(filterAtom);

  return (
    <>
      <div className={styles.main}>
        <Head>
          <title>Pokemon</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico'/>
        </Head>
        <div>
          <input className={styles.search}
           type='text'
           value={filter}
           onChange={(e) => setFilter(e.target.value)}
          />
        </div>
        <div className={styles.container}>
          {pokemon.slice(0,20).map((p) => (
            <div key={p.id} className={styles.image} >
              <img
                alt={p.name}
                src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${p.image}`} 
               />
               <h2>{p.name}</h2>
            </div>
          ))};
        </div>
      </div>
    </>
  )
}
